language: en
pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "EmbeddingIntentClassifier"
- name: DucklingHTTPExtractor
  url: http://localhost:8000
  dimensions:
  - email
policies:
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.8
- name: AugmentedMemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
- name: EmbeddingPolicy
