name: Lint and Test PR
on:
  pull_request:
    paths-ignore:
    - "README.md"
    - "Makefile"
    - "Dockerfile"

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  type-testing:
    name: Type Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Type Checking
      working-directory: ${{ github.workspace }}
      run: |
        make types
  data-validation:
    name: Rasa Data Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Rasa Data Validation
      working-directory: ${{ github.workspace }}
      run: |
        make validate
  training-testing:
    name: Training and Testing
    runs-on: ubuntu-latest
    needs: [data-validation]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install -U 'pip<20'
          pip install -r requirements-dev.txt
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          test_type: all
          cross_validation: true
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models


  # training-testing:
  #   name: Testing Stories
  #   runs-on: ubuntu-latest
  #   needs: [data-validation]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.6
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install -U 'pip<20'
  #       pip install -r requirements-dev.txt
  #   - name: Test Training Stories
  #     working-directory: ${{ github.workspace }}
  #     run: |
  #       make test
  #   - name: Cross-validate NLU model
  #     run: |
  #       make crossval
  #   - name: post cross-val results to PR
  #     uses: amn41/comment-on-pr@comment-file-contents
  #     continue-on-error: true
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       msg: results.md
  #   - name: Upload model
  #     if: github.ref == 'refs/heads/master'
  #     uses: actions/upload-artifact@master
  #     with:
  #       name: model
  #       path: models