name: Lint and Test
on:
  push:
    branches:
      - master
    paths-ignore:
    - "README.md"
    - "Makefile"
    - "Dockerfile"

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  type-testing:
    name: Type Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Type Checking
      working-directory: ${{ github.workspace }}
      run: |
        make types
  my_first_job:
    steps:
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@master
        with:
          test_type: nlu
  # data-validation:
  #   name: Rasa Data Validation
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.6
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install -U 'pip<20'
  #       pip install -r requirements-dev.txt
  #   - name: Rasa Data Validation
  #     working-directory: ${{ github.workspace }}
  #     run: |
  #       make validate
  # training-testing:
  #   name: Testing Stories
  #   runs-on: ubuntu-latest
  #   needs: [data-validation]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.6
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install -U 'pip<20'
  #       pip install -r requirements-dev.txt
  #   - name: Test Training Stories
  #     working-directory: ${{ github.workspace }}
  #     run: |
  #       make test
