name: Lint and Test PR
on:
  pull_request:
    paths-ignore:
    - "README.md"
    - "Makefile"
    - "Dockerfile"

jobs:
  lint-testing:
    name: Code Formatting Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Code Formatting Tests
      working-directory: ${{ github.workspace }}
      run: |
        make lint
  type-testing:
    name: Type Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install -U 'pip<20'
        pip install -r requirements-dev.txt
    - name: Type Checking
      working-directory: ${{ github.workspace }}
      run: |
        make types
  training:
    name: Training Model
    runs-on: ubuntu-latest
    needs: [lint-testing, type-testing]
    env:
      RASA_VERSION: 2.1.3
      RUN_TRAINING: false
    steps:
      - uses: actions/checkout@v1
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Did Training Data Change
        if: |
            contains(  steps.files.outputs.all, 'data/' )
            || contains(  steps.files.outputs.all, 'config.yml' )
            || contains(  steps.files.outputs.all, 'domain.yml' )
        run: echo "RUN_TRAINING=true" >> $GITHUB_ENV
      - name: Rasa Train
        if: env.RUN_TRAINING == 'true'
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: ${{ env.RASA_VERSION }}
          rasa_test: false
          data_validate: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test-model:
    name: Test Model
    if: env.RUN_TRAINING == 'true'
    runs-on: ubuntu-latest
    needs: [training]
    env:
      RASA_VERSION: 2.1.3
    steps:
      - uses: actions/checkout@v1
      - name: Rasa Train and Test GitHub Action
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: ${{ env.RASA_VERSION }}
          rasa_train: false
          test_type: all
          data_validate: true
          cross_validation: true
          publish_summary: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload model
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@master
        with:
          name: model
          path: models
